// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env, PrismaConfig } from '@prisma/config';
import { config } from 'dotenv';
import 'dotenv/config';

config({
  path: `.env.${process.env.NODE_ENV}`,
});

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
}) satisfies PrismaConfig;
